steps:
  # ---------------------------------------------------------
  # Verify Substitutions & Identity
  # Some debug/environment output
  # ---------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "******************************************************"
        echo "Build Triggered Successfully!"
        echo "commit sha: $COMMIT_SHA"
        echo "built from branch: $BRANCH_NAME"
        echo "project id: $PROJECT_ID"
        echo "******************************************************"
        echo "Currently running as:"
        gcloud auth list
        echo "******************************************************"
        echo "Checking access to Cloud Storage..."
        gsutil ls gs:// || echo "WARNING: Could not list buckets. Check permissions."
        ## position our tfvars file retrieved from secret manager
        echo "Retrieving terraform.tfvars from Secret Manager..."
        gcloud secrets versions access latest \
                  --secret="tfvars" \
                  --project="$PROJECT_ID" > cicd/dev/terraform.auto.tfvars
        ## extract bucket name from tfvars for backend config
        BUCKET_NAME=$(grep 'bucket' cicd/dev/terraform.auto.tfvars | awk -F'"' '{print $$2}')
        echo "Found Bucket: $$BUCKET_NAME"
        echo "$$BUCKET_NAME" > /workspace/backend_bucket.txt
  # ---------------------------------------------------------
  # Terraform Init
  # ---------------------------------------------------------   
  - name: 'hashicorp/terraform:light'
    dir: 'cicd/dev'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # 1. Install Python (required for gcloud)
        apk add --update python3 curl bash

        # 2. Download and install gcloud
        curl -sSL https://sdk.cloud.google.com | bash
        export PATH=$PATH:/root/google-cloud-sdk/bin

        TF_BUCKET=$(cat /workspace/backend_bucket.txt)
        echo "Running Terraform Init..."
        terraform init \
          -backend-config="bucket=$${TF_BUCKET}"
        echo "APPLYING Terraform..."
        terraform apply -auto-approve

options:
  logging: CLOUD_LOGGING_ONLY