steps:
  # ---------------------------------------------------------
  # Step 1: Verify Code Checkout
  # This proves that Cloud Build successfully pulled your repo.
  # ---------------------------------------------------------
  - name: 'ubuntu'
    args: ['ls', '-la']

  # ---------------------------------------------------------
  # Step 2: Verify Substitutions & Identity
  # This proves which Branch triggered the build and which Service Account is running it.
  # ---------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "******************************************************"
        echo "Build Triggered Successfully!"
        echo "commit sha: $COMMIT_SHA"
        echo "built from branch: $BRANCH_NAME"
        echo "project id: $PROJECT_ID"
        echo "******************************************************"
        echo "Currently running as:"
        gcloud auth list
        echo "******************************************************"

  # ---------------------------------------------------------
  # Step 3: Verify Network/API Access (Optional)
  # This proves your Service Account has basic read permissions.
  # ---------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking access to Cloud Storage..."
        gsutil ls gs:// || echo "WARNING: Could not list buckets. Check permissions."

options:
  logging: CLOUD_LOGGING_ONLY