steps:
  # ---------------------------------------------------------
  # Verify Substitutions & Identity
  # Some debug/environment output
  # ---------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "******************************************************"
        echo "Build Triggered Successfully!"
        echo "commit sha: $COMMIT_SHA"
        echo "built from branch: $BRANCH_NAME"
        echo "project id: $PROJECT_ID"
        echo "******************************************************"
        echo "Currently running as:"
        gcloud auth list
        echo "******************************************************"
        echo "Checking access to Cloud Storage..."
        gsutil ls gs:// || echo "WARNING: Could not list buckets. Check permissions."
  # ---------------------------------------------------------
  # Terraform Init
  # ---------------------------------------------------------   
  - name: 'hashicorp/terraform:light'
    workingDir: 'cicd/dev'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Running Terraform Plan..."
        terraform plan

options:
  logging: CLOUD_LOGGING_ONLY